disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Telstra_AssignmentTests
 - Telstra_AssignmentUITests

line_length: 200